DEPARTAMENTOS = {
    "Amazonas": "91",
    "Antioquia": "05",
    "Arauca": "81",
    "Atlántico": "08",
    "Bogotá D.C.": "11",
    "Bolívar": "13",
    "Boyacá": "15",
    "Caldas": "17",
    "Caquetá": "18",
    "Casanare": "85",
    "Cauca": "19",
    "Cesar": "20",
    "Chocó": "27",
    "Córdoba": "23",
    "Cundinamarca": "25",
    "Guainía": "94",
    "Guaviare": "95",
    "Huila": "41",
    "La Guajira": "44",
    "Magdalena": "47",
    "Meta": "50",
    "Nariño": "52",
    "Norte De Santander": "54",
    "Putumayo": "86",
    "Quindío": "63",
    "Risaralda": "66",
    "San Andrés": "88",
    "Santander": "68",
    "Sucre": "70",
    "Tolima": "73",
    "Valle Del Cauca": "76",
    "Vaupés": "97",
    "Vichada": "99"
}

DEPARTAMENTOS_INVERTIDO = {
    "91": "Amazonas",
    "05": "Antioquia",
    "81": "Arauca",
    "08": "Atlántico",
    "11": "Bogotá D.C.",
    "13": "Bolívar",
    "15": "Boyacá",
    "17": "Caldas",
    "18": "Caquetá",
    "85": "Casanare",
    "19": "Cauca",
    "20": "Cesar",
    "27": "Chocó",
    "23": "Córdoba",
    "25": "Cundinamarca",
    "94": "Guainía",
    "95": "Guaviare",
    "41": "Huila",
    "44": "La Guajira",
    "47": "Magdalena",
    "50": "Meta",
    "52": "Nariño",
    "54": "Norte De Santander",
    "86": "Putumayo",
    "63": "Quindío",
    "66": "Risaralda",
    "88": "San Andrés",
    "68": "Santander",
    "70": "Sucre",
    "73": "Tolima",
    "76": "Valle Del Cauca",
    "97": "Vaupés",
    "99": "Vichada"
}


